In [2]:
import pandas as pd

In [3]:
main_df = pd.read_csv(r"D:\GUVI\Projects\International Debt_project2\Debt_python\csv\IDS_ALLCountries_Data.csv",encoding="latin1")
country_meta = pd.read_csv(r"D:\GUVI\Projects\International Debt_project2\Debt_python\csv\IDS_CountryMetaData.csv",encoding='latin1')
series_meta = pd.read_csv(r"D:\GUVI\Projects\International Debt_project2\Debt_python\csv\IDS_SeriesMetaData.csv",encoding='latin1')
country_series = pd.read_csv(r"D:\GUVI\Projects\International Debt_project2\Debt_python\csv\Country-Series - Metadata.csv",encoding='latin1')
foot_notes = pd.read_csv(r"D:\GUVI\Projects\International Debt_project2\Debt_python\csv\IDS_FootNoteMetaData.csv",encoding='latin1')

-----------------------------------------Displaying the AllCountires Dataset------------------------------

In [4]:
pd.DataFrame(main_df.head())

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,2000,2001,2002,2003,...,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(main_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 62983 entries, 0 to 62982
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country Name           62980 non-null  str
 1   Country Code           62978 non-null  str
 2   Counterpart-Area Name  62978 non-null  str
 3   Counterpart-Area Code  62978 non-null  str
 4   Series Name            62978 non-null  str
 5   Series Code            62978 non-null  str
 6   2000                   49490 non-null  float64
 7   2001                   49434 non-null  float64
 8   2002                   49262 non-null  float64
 9   2003                   49001 non-null  float64
 10  2004                   49195 non-null  float64
 11  2005                   49137 non-null  float64
 12  2006                   49394 non-null  float64
 13  2007                   49645 non-null  float64
 14  2008                   49497 non-null  float64
 15  2009                   49768 non-null  float64
 16  2010                   49761 non-null  float64
 17  2011                   49080 non-null  float64
 18  2012                   49008 non-null  float64
 19  2013                   49379 non-null  float64
 20  2014                   50504 non-null  float64
 21  2015                   50431 non-null  float64
 22  2016                   50192 non-null  float64
 23  2017                   50333 non-null  float64
 24  2018                   50296 non-null  float64
 25  2019                   50493 non-null  float64
 26  2020                   50956 non-null  float64
 27  2021                   50727 non-null  float64
 28  2022                   50721 non-null  float64
 29  2023                   50641 non-null  float64
 30  2024                   50590 non-null  float64
 31  2025                   12855 non-null  float64
 32  2026                   12760 non-null  float64
 33  2027                   12622 non-null  float64
 34  2028                   12432 non-null  float64
 35  2029                   12138 non-null  float64
 36  2030                   11967 non-null  float64
 37  2031                   11771 non-null  float64
 38  2032                   11566 non-null  float64
dtypes: float64(33), str(6)
memory usage: 18.7 MB
None

In [6]:
print("\n Columns",main_df.columns)
print(main_df.describe())

 Columns Index(['Country Name', 'Country Code', 'Counterpart-Area Name',
       'Counterpart-Area Code', 'Series Name', 'Series Code', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028',
       '2029', '2030', '2031', '2032'],
      dtype='str')
               2000          2001          2002          2003          2004  \
count  4.949000e+04  4.943400e+04  4.926200e+04  4.900100e+04  4.919500e+04
mean   3.632014e+09  3.589615e+09  3.659750e+09  4.109777e+09  4.536444e+09
std    5.292695e+10  5.308864e+10  5.449395e+10  6.107004e+10  7.054690e+10
min   -8.487669e+10 -5.573282e+10 -7.292274e+10 -5.500037e+10 -3.736228e+10
25%    1.112442e+00  3.541816e-01  7.421391e-01  1.116054e-01  5.356484e-01
50%    9.046966e+06  8.033068e+06  7.674301e+06  8.706365e+06  9.689430e+06
75%    1.725729e+08  1.660500e+08  1.715300e+08  1.868751e+08  2.174472e+08
max    5.440000e+12  5.450000e+12  5.560000e+12  6.220000e+12  7.290000e+12

               2005          2006          2007          2008          2009  \
count  4.913700e+04  4.939400e+04  4.964500e+04  4.949700e+04  4.976800e+04
mean   4.738496e+09  5.190393e+09  6.182575e+09  6.752879e+09  6.849177e+09
std    8.035767e+10  9.357806e+10  1.147883e+11  1.365185e+11  1.357978e+11
min   -7.343440e+10 -7.145644e+10 -5.255350e+10 -6.940197e+10 -4.432376e+10
25%    7.739000e-01  9.361400e-01  2.862026e+00  3.052400e+00  5.876775e+00
50%    9.915805e+06  1.046313e+07  1.172750e+07  1.261500e+07  1.515973e+07
75%    2.195815e+08  2.196477e+08  2.781230e+08  2.915208e+08  3.518703e+08
max    8.580000e+12  1.010000e+13  1.250000e+13  1.490000e+13  1.490000e+13

       ...          2023          2024          2025          2026  \
count  ...  5.064100e+04  5.059000e+04  1.285500e+04  1.276000e+04
mean   ...  1.649637e+10  1.736519e+10  6.308260e+09  5.571382e+09
std    ...  3.389385e+11  3.512324e+11  3.737201e+10  3.200925e+10
min    ... -2.590000e+11 -2.320000e+11  0.000000e+00  0.000000e+00
25%    ...  0.000000e+00  0.000000e+00  1.819800e+07  1.736757e+07
50%    ...  3.397000e+07  3.286379e+07  1.747302e+08  1.683518e+08
75%    ...  7.984620e+08  8.363163e+08  1.275588e+09  1.228297e+09
max    ...  3.680000e+13  3.820000e+13  1.170000e+12  1.000000e+12

               2027          2028          2029          2030          2031  \
count  1.262200e+04  1.243200e+04  1.213800e+04  1.196700e+04  1.177100e+04
mean   5.184003e+09  4.809777e+09  4.085452e+09  5.141240e+09  3.242091e+09
std    2.969469e+10  2.622276e+10  2.201532e+10  3.087435e+10  1.687863e+10
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    1.692255e+07  1.508966e+07  1.359342e+07  1.182594e+07  1.033100e+07
50%    1.612748e+08  1.386245e+08  1.220880e+08  1.077675e+08  9.936185e+07
75%    1.142909e+09  9.780040e+08  8.999615e+08  7.999839e+08  8.112449e+08
max    9.180000e+11  7.740000e+11  6.570000e+11  7.330000e+11  4.810000e+11

               2032
count  1.156600e+04
mean   2.706323e+09
std    1.380838e+10
min    0.000000e+00
25%    8.062213e+06
50%    8.007778e+07
75%    6.457404e+08
max    3.820000e+11

[8 rows x 33 columns]

In [7]:
print(main_df.isnull().sum())

Country Name                 3
Country Code                 5
Counterpart-Area Name        5
Counterpart-Area Code        5
Series Name                  5
Series Code                  5
2000                     13493
2001                     13549
2002                     13721
2003                     13982
2004                     13788
2005                     13846
2006                     13589
2007                     13338
2008                     13486
2009                     13215
2010                     13222
2011                     13903
2012                     13975
2013                     13604
2014                     12479
2015                     12552
2016                     12791
2017                     12650
2018                     12687
2019                     12490
2020                     12027
2021                     12256
2022                     12262
2023                     12342
2024                     12393
2025                     50128
2026                     50223
2027                     50361
2028                     50551
2029                     50845
2030                     51016
2031                     51212
2032                     51417
dtype: int64

In [8]:
afterclean_main_df = main_df.iloc[:-5]
print("Before column row",main_df.shape)
print("After column row",afterclean_main_df.shape)

Before column row (62983, 39)
After column row (62978, 39)

In [9]:
last_8 = afterclean_main_df.iloc[:,-8:]
b=last_8.isnull().any(axis=1).sum()/len(last_8)*100
print(f'{round(b)}%')
print("Before column column",afterclean_main_df.shape)
afterclean_main_df= afterclean_main_df.drop(columns=afterclean_main_df.columns[-8:])
print("After column column",afterclean_main_df.shape)
afterclean_main_df.drop_duplicates(inplace=True)

82%
Before column column (62978, 39)
After column column (62978, 31)

In [10]:
print(afterclean_main_df.isnull().sum()/len(afterclean_main_df)*100)

Country Name              0.000000
Country Code              0.000000
Counterpart-Area Name     0.000000
Counterpart-Area Code     0.000000
Series Name               0.000000
Series Code               0.000000
2000                     21.417003
2001                     21.505923
2002                     21.779034
2003                     22.193464
2004                     21.885420
2005                     21.977516
2006                     21.569437
2007                     21.170885
2008                     21.405888
2009                     20.975579
2010                     20.986694
2011                     22.068024
2012                     22.182349
2013                     21.593255
2014                     19.806917
2015                     19.922830
2016                     20.302328
2017                     20.078440
2018                     20.137191
2019                     19.824383
2020                     19.089206
2021                     19.452825
2022                     19.462352
2023                     19.589380
2024                     19.670361
dtype: float64

In [11]:
import numpy as np
afterclean_main_df = afterclean_main_df.replace(["", " ", "..", "NA", "N/A"], np.nan)
afterclean_main_df.fillna(0, inplace=True)
print(afterclean_main_df.isnull().sum())

Country Name             0
Country Code             0
Counterpart-Area Name    0
Counterpart-Area Code    0
Series Name              0
Series Code              0
2000                     0
2001                     0
2002                     0
2003                     0
2004                     0
2005                     0
2006                     0
2007                     0
2008                     0
2009                     0
2010                     0
2011                     0
2012                     0
2013                     0
2014                     0
2015                     0
2016                     0
2017                     0
2018                     0
2019                     0
2020                     0
2021                     0
2022                     0
2023                     0
2024                     0
dtype: int64

In [12]:
afterclean_main_df.columns = afterclean_main_df.columns.str.strip()
print(afterclean_main_df.columns)
print(afterclean_main_df.shape)

Index(['Country Name', 'Country Code', 'Counterpart-Area Name',
       'Counterpart-Area Code', 'Series Name', 'Series Code', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024'],
      dtype='str')
(62978, 31)

In [13]:
filtered_df = afterclean_main_df[["Country Name","Country Code" ,"Series Name",'2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024']]
print(filtered_df.columns)

Index(['Country Name', 'Country Code', 'Series Name', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023', '2024'],
      dtype='str')

In [116]:

#Analyze country-wise debt distribution

df = filtered_df.copy()
year_cols = [col for col in df.columns if col.isdigit()]

df[year_cols] = df[year_cols].apply(pd.to_numeric)
df

#year wise debt-2006
print("Year-2006 debt of all countries\n",df.groupby('Country Name')['2007'].sum())

#year wise debt
country_data = df.groupby('Country Name')[year_cols].sum()
country_data

#Total Debt
country_data['Total_Debt'] = country_data.sum(axis=1)
print(country_data[['Total_Debt']])

Year-2006 debt of all countries
 Country Name
Afghanistan    5.740144e+10
Albania        6.772501e+10
Algeria        4.747922e+11
Angola         5.420249e+11
Argentina      1.940198e+12
                   ...
Vanuatu        2.788777e+09
Viet Nam       6.692038e+11
Yemen, Rep.    1.571982e+11
Zambia         6.169556e+10
Zimbabwe       7.613371e+10
Name: 2007, Length: 134, dtype: float64
                Total_Debt
Country Name
Afghanistan   1.202846e+12
Albania       2.771164e+12
Algeria       1.191236e+13
Angola        2.065473e+13
Argentina     6.912848e+13
...                    ...
Vanuatu       1.415127e+11
Viet Nam      3.789187e+13
Yemen, Rep.   3.521307e+12
Zambia        5.493606e+12
Zimbabwe      3.087925e+12

[134 rows x 1 columns]

In [ ]:
country_sorted = country_data.sort_values(by='Total_Debt', ascending=False)


print("Highest debt\n",country_sorted[['Total_Debt']].head(10))

print("\nlowest debt\n",country_sorted[['Total_Debt']].tail(10))

Highest debt
                                                      Total_Debt
Country Name
Low & middle income                                2.354287e+15
Middle income                                      2.286732e+15
Upper middle income                                1.681354e+15
East Asia & Pacific (excluding high income)        8.796106e+14
China                                              6.083933e+14
Lower middle income                                6.053554e+14
Latin America & Caribbean (excluding high income)  5.691093e+14
IDA total                                          2.927440e+14
Europe & Central Asia (excluding high income)      2.579855e+14
South Asia                                         2.323280e+14

lowest debt
                                   Total_Debt
Country Name
Equatorial Guinea               2.325492e+11
Timor-Leste                     2.077726e+11
St. Vincent and the Grenadines  2.075162e+11
Samoa                           1.778766e+11
Comoros                         1.586370e+11
Dominica                        1.565170e+11
Solomon Islands                 1.564889e+11
Vanuatu                         1.415127e+11
Sao Tome and Principe           1.211597e+11
Tonga                           8.419110e+10
Total_Debt    True
dtype: bool

In [57]:
analysis_df = filtered_df[
    filtered_df['Series Name'].str.contains('debt per capita', case=False)
].copy()     

year_cols = [col for col in analysis_df.columns if col.isdigit()]

analysis_df['Avg_Debt_Per_Capita'] = analysis_df[year_cols].mean(axis=1)
country_rank = analysis_df[['Country Name', 'Avg_Debt_Per_Capita']]\
    .sort_values(by='Avg_Debt_Per_Capita', ascending=False)

country_rank.head(10)
analysis_df

,Country Name,Country Code,Series Name,2000,2001,2002,2003,2004,2005,2006,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Avg_Debt_Per_Capita
288,Afghanistan,AFG,Total external debt per capita (US$),0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,38.520331,...,74.812804,77.110360,72.905249,70.310584,77.812945,88.893693,83.621096,82.695374,78.412486,59.416939
806,Albania,ALB,Total external debt per capita (US$),363.239047,377.204084,387.081596,510.198646,530.061458,706.279904,841.405275,...,2960.960609,3411.067273,3366.975164,3249.408005,3692.110383,3931.830661,3751.373351,4120.588940,3946.277063,2227.002089
1309,Algeria,DZA,Total external debt per capita (US$),823.896612,726.048945,725.588960,738.746232,687.005229,515.929865,175.452641,...,133.731834,136.889306,134.348611,126.860762,117.566615,164.848059,156.764908,158.461840,147.353911,285.685622
1814,Angola,AGO,Total external debt per capita (US$),602.874007,524.082415,526.269340,507.954998,526.933657,634.403077,494.880985,...,1968.062220,1942.986424,1974.348473,1924.044596,1955.247556,1911.817462,1696.245218,1558.456348,1550.263881,1263.972189
2362,Argentina,ARG,Total external debt per capita (US$),4032.433834,4057.159852,3900.150711,4253.630254,4328.112103,3335.012670,3001.385288,...,4137.494104,5101.142674,6221.620906,6241.093418,5655.940672,5431.514415,5483.112606,5551.224882,5303.665801,4260.904652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61115,Vanuatu,VUT,Total external debt per capita (US$),602.658204,642.115280,819.880512,802.736929,748.292364,476.121975,512.144163,...,1078.408379,1441.328943,1410.075834,1454.603892,1472.087845,1558.661932,1480.401040,1468.946649,1586.067796,961.079623
61613,Viet Nam,VNM,Total external debt per capita (US$),166.435651,162.023054,169.386695,195.981115,219.460552,229.299911,228.221082,...,962.595488,1154.619194,1170.252732,1260.586727,1320.149725,1413.578243,1470.915187,1413.472683,1316.074718,722.890103
62004,"Yemen, Rep.",YEM,Total external debt per capita (US$),262.554826,256.483641,255.504036,255.431360,253.601385,240.348350,242.694241,...,219.965416,217.373813,206.438973,200.938084,197.062765,204.673766,192.321164,184.891458,174.625980,232.934025
62494,Zambia,ZMB,Total external debt per capita (US$),580.225026,599.919182,627.456091,626.593779,665.751801,458.238906,185.548550,...,931.499110,1361.091800,1369.565431,1587.818209,1549.441214,1374.413944,1410.385236,1403.038078,1319.155212,785.542844
62969,Zimbabwe,ZWE,Total external debt per capita (US$),333.551871,317.985916,343.787450,393.438139,419.495886,377.207185,411.920992,...,809.259228,868.484380,863.633187,821.199309,839.457702,893.262655,878.756207,890.318376,865.902209,617.379148

In [15]:
# Total across all years (per country)
analysis_df['Total_Debt_Per_Capita'] = analysis_df[year_cols].sum(axis=1)

country_dist = analysis_df[['Country Name', 'Total_Debt_Per_Capita']]\
    .sort_values(by='Total_Debt_Per_Capita', ascending=False)

# Percentage
total = country_dist['Total_Debt_Per_Capita'].sum()
country_dist['Percentage'] = (country_dist['Total_Debt_Per_Capita'] / total) * 100

print(country_dist.head(10))

      Country Name  Total_Debt_Per_Capita  Percentage
32125      Lebanon          221066.250872    4.475045
40640   Montenegro          191627.633482    3.879119
37599    Mauritius          182922.682457    3.702904
28891   Kazakhstan          159369.267469    3.226113
14018     Dominica          142779.503817    2.890286
40194     Mongolia          128877.180531    2.608861
21470      Grenada          124593.763529    2.522152
2362     Argentina          106522.616299    2.156338
27951      Jamaica          106512.529920    2.156133
58202      Turkiye          105186.433977    2.129289

------------------------------------------------Country-Meta-Data-----------------------------------------

In [16]:
#Display CountryMeta
pd.DataFrame(country_meta)

,Code,Long Name,Income Group,Region,Lending category,Other groups,Currency Unit,Latest population census,Latest household survey,Special Notes,...,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,2-alpha code,WB-2 code,Table Name,Short Name
0,AFG,Islamic State of Afghanistan,Low income,Middle East & North Africa,IDA,HIPC,Afghan afghani,1979,Multiple Indicator Cluster Survey 2022-2023,The reporting period for national accounts dat...,...,"Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,2000.0,AF,AF,Afghanistan,Afghanistan
1,ALB,Republic of Albania,Upper middle income,Europe & Central Asia,IBRD,NaN,Albanian lek,2023,Demographic and Health Survey 2017 - 2018,NaN,...,Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2018.0,2006.0,AL,AL,Albania,Albania
2,DZA,People's Democratic Republic of Algeria,Upper middle income,Middle East & North Africa,IBRD,NaN,Algerian dinar,2022,Multiple Indicator Cluster Survey 2018-2019,NaN,...,"Integrated household survey (IHS), 2011",NaN,NaN,2010.0,2017.0,2012.0,DZ,DZ,Algeria,Algeria
3,AGO,People's Republic of Angola,Lower middle income,Sub-Saharan Africa,IBRD,NaN,Angolan kwanza,2014,Demographic and Health Survey 2015/16,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2018.0,2005.0,AO,AO,Angola,Angola
4,ARG,Argentine Republic,Upper middle income,Latin America & Caribbean,IBRD,NaN,Argentine peso,2022,Multiple Indicator Cluster Survey 2019-2020,The World Bank systematically assesses the app...,...,"Integrated household survey (IHS), 2016",Yes,2008,2002.0,2018.0,2011.0,AR,AR,Argentina,Argentina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,VUT,Republic of Vanuatu,Lower middle income,East Asia & Pacific,IDA,NaN,Vanuatu vatu,2016,Multiple Indicator Cluster Survey 2007,NaN,...,"Integrated household survey (IHS), 2010",NaN,2007,NaN,2011.0,NaN,VU,VU,Vanuatu,Vanuatu
130,VNM,Socialist Republic of Viet Nam,Lower middle income,East Asia & Pacific,IBRD,NaN,Vietnamese dong,2019,Multiple Indicator Cluster Survey 2020-2021,NaN,...,"Integrated household survey (IHS), 2016",Yes,2016,2013.0,2017.0,2005.0,VN,VN,Viet Nam,Viet Nam
131,YEM,Republic of Yemen,Low income,Middle East & North Africa,IDA,NaN,Yemeni rial,2004,National Health and Demographic Survey 2013,The World Bank systematically assesses the app...,...,"Expenditure survey/budget survey (ES/BS), 2014",NaN,NaN,2012.0,2015.0,2005.0,YE,RY,"Yemen, Rep.","Yemen, Republic of"
132,ZMB,Republic of Zambia,Lower middle income,Sub-Saharan Africa,IDA,HIPC,New Zambian kwacha,2022,Demographic and Health Survey 2018,National accounts data were rebased to reflect...,...,"Integrated household survey (IHS), 2015",NaN,NaN,1994.0,2018.0,2002.0,ZM,ZM,Zambia,Zambia
133,ZWE,Republic of Zimbabwe,Lower middle income,Sub-Saharan Africa,Blend,NaN,Zimbabwean Zimbabwe Gold,2022,Multiple Indicator Cluster Survey 2019,National Accounts data are reported in Zimbabw...,...,"Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2018.0,2007.0,ZW,ZW,Zimbabwe,Zimbabwe

In [17]:
print(country_meta.info())

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 30 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Code                                               134 non-null    str
 1   Long Name                                          134 non-null    str
 2   Income Group                                       119 non-null    str
 3   Region                                             120 non-null    str
 4   Lending category                                   120 non-null    str
 5   Other groups                                       40 non-null     str
 6   Currency Unit                                      120 non-null    str
 7   Latest population census                           118 non-null    str
 8   Latest household survey                            120 non-null    str
 9   Special Notes                                      60 non-null     str
 10  National accounts base year                        120 non-null    str
 11  National accounts reference year                   39 non-null     float64
 12  System of National Accounts                        120 non-null    str
 13  SNA price valuation                                120 non-null    str
 14  PPP survey years                                   116 non-null    str
 15  Balance of Payments Manual in use                  118 non-null    str
 16  External debt Reporting status                     120 non-null    str
 17  System of trade                                    100 non-null    str
 18  Government Accounting concept                      97 non-null     str
 19  IMF data dissemination standard                    117 non-null    str
 20  Source of most recent Income and expenditure data  116 non-null    str
 21  Vital registration complete                        36 non-null     str
 22  Latest agricultural census                         71 non-null     str
 23  Latest industrial data                             85 non-null     float64
 24  Latest trade data                                  113 non-null    float64
 25  Latest water withdrawal data                       112 non-null    float64
 26  2-alpha code                                       134 non-null    str
 27  WB-2 code                                          134 non-null    str
 28  Table Name                                         134 non-null    str
 29  Short Name                                         134 non-null    str
dtypes: float64(4), str(26)
memory usage: 31.5 KB
None

In [18]:
print("\n Columns",country_meta.columns)
print(country_meta.describe())

 Columns Index(['Code', 'Long Name', 'Income Group', 'Region', 'Lending category',
       'Other groups', 'Currency Unit', 'Latest population census',
       'Latest household survey', 'Special Notes',
       'National accounts base year', 'National accounts reference year',
       'System of National Accounts', 'SNA price valuation',
       'PPP survey years', 'Balance of Payments Manual in use',
       'External debt Reporting status', 'System of trade',
       'Government Accounting concept', 'IMF data dissemination standard',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data',
       'Latest water withdrawal data', '2-alpha code', 'WB-2 code',
       'Table Name', 'Short Name'],
      dtype='str')
       National accounts reference year  Latest industrial data  \
count                         39.000000               85.000000
mean                        2012.589744             2004.788235
std                            5.892537               10.116105
min                         2000.000000             1973.000000
25%                         2008.500000             1999.000000
50%                         2014.000000             2010.000000
75%                         2016.500000             2012.000000
max                         2022.000000             2014.000000

       Latest trade data  Latest water withdrawal data
count         113.000000                    112.000000
mean         2016.371681                   2005.928571
std             3.706160                      4.267443
min          1995.000000                   1993.000000
25%          2017.000000                   2003.000000
50%          2018.000000                   2005.000000
75%          2018.000000                   2009.250000
max          2018.000000                   2016.000000

In [19]:
print(country_meta.isnull().sum())

Code                                                  0
Long Name                                             0
Income Group                                         15
Region                                               14
Lending category                                     14
Other groups                                         94
Currency Unit                                        14
Latest population census                             16
Latest household survey                              14
Special Notes                                        74
National accounts base year                          14
National accounts reference year                     95
System of National Accounts                          14
SNA price valuation                                  14
PPP survey years                                     18
Balance of Payments Manual in use                    16
External debt Reporting status                       14
System of trade                                      34
Government Accounting concept                        37
IMF data dissemination standard                      17
Source of most recent Income and expenditure data    18
Vital registration complete                          98
Latest agricultural census                           63
Latest industrial data                               49
Latest trade data                                    21
Latest water withdrawal data                         22
2-alpha code                                          0
WB-2 code                                             0
Table Name                                            0
Short Name                                            0
dtype: int64

In [20]:
country_meta.columns = country_meta.columns.str.strip()

In [21]:
country_meta = country_meta.drop_duplicates()

In [22]:
country_meta_filtered = country_meta[
    ["Code", "Income Group", "Region"]
]
print(country_meta_filtered.isnull().sum())

Code             0
Income Group    15
Region          14
dtype: int64

In [23]:
country_meta_filtered = country_meta_filtered.replace(["", " ", "NA"], np.nan)

country_meta_filtered["Income Group"] = country_meta_filtered["Income Group"].fillna("Unknown")
country_meta_filtered["Region"] = country_meta_filtered["Region"].fillna("Unknown")
print(country_meta_filtered.isnull().sum())
country_meta_filtered= country_meta_filtered.rename(columns={'Code':'Country Code'})

Code            0
Income Group    0
Region          0
dtype: int64

In [24]:
country_meta_filtered.columns = (country_meta_filtered.columns.str.strip().str.lower().str.replace(" ", "_"))

In [25]:
pd.DataFrame(country_meta_filtered)

    country_code         income_group                      region
0            AFG           Low income  Middle East & North Africa
1            ALB  Upper middle income       Europe & Central Asia
2            DZA  Upper middle income  Middle East & North Africa
3            AGO  Lower middle income          Sub-Saharan Africa
4            ARG  Upper middle income   Latin America & Caribbean
..           ...                  ...                         ...
129          VUT  Lower middle income         East Asia & Pacific
130          VNM  Lower middle income         East Asia & Pacific
131          YEM           Low income  Middle East & North Africa
132          ZMB  Lower middle income          Sub-Saharan Africa
133          ZWE  Lower middle income          Sub-Saharan Africa

[134 rows x 3 columns]

--------------------------------------------Series-Meta-Data--------------------------------------------

In [26]:
#Display SeriesMetaData
pd.DataFrame(series_meta)

,Code,License Type,Indicator Name,Short definition,Long definition,Source,Topic,Dataset,Periodicity,Aggregation method,Limitations and exceptions,General comments
0,DT.GPA.DPPG,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
1,DT.GPA.OFFT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
2,DT.GPA.PRVT,NaN,Average grace period on new external debt comm...,Grace period is the period from the date of si...,Grace period is the period from the date of si...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
3,DT.GRE.DPPG,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
4,DT.GRE.OFFT,NaN,Average grant element on new external debt com...,The grant element of a loan is the grant equiv...,The grant element of a loan is the grant equiv...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Terms,International Debt Statistics,Annual,Weighted average,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
569,FI.RES.TOTL.MO,NaN,Total reserves in months of imports,Total reserves comprise holdings of monetary g...,Total reserves comprise holdings of monetary g...,"International Monetary Fund, International Fin...",Economic Policy & Debt: Balance of payments: R...,International Debt Statistics,Annual,Weighted average,NaN,NaN
570,DT.UND.OFFT.CD,NaN,"Undisbursed external debt, official creditors ...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN,NaN
571,DT.UND.PRVT.CD,NaN,"Undisbursed external debt, private creditors (...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN,NaN
572,DT.UND.DPPG.CD,NaN,"Undisbursed external debt, total (UND, current...",Undisbursed debt is the total public and publi...,Undisbursed debt is the total public and publi...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Undisbu...,International Debt Statistics,Annual,Sum,NaN,NaN
573,DT.DOD.DIMF.CD,NaN,"Use of IMF credit (DOD, current US$)",Use of IMF credit denotes members drawings on...,Use of IMF Credit: Data related to the operati...,"World Bank, International Debt Statistics.",Economic Policy & Debt: External debt: Debt ou...,International Debt Statistics,Annual,Sum,NaN,NaN

In [27]:
print(series_meta.info())

<class 'pandas.DataFrame'>
RangeIndex: 574 entries, 0 to 573
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Code                        574 non-null    str
 1   License Type                2 non-null      str
 2   Indicator Name              574 non-null    str
 3   Short definition            572 non-null    str
 4   Long definition             574 non-null    str
 5   Source                      574 non-null    str
 6   Topic                       574 non-null    str
 7   Dataset                     573 non-null    str
 8   Periodicity                 574 non-null    str
 9   Aggregation method          574 non-null    str
 10  Limitations and exceptions  1 non-null      str
 11  General comments            8 non-null      str
dtypes: str(12)
memory usage: 53.9 KB
None

In [28]:
print(series_meta.describe())
print(series_meta.columns)

               Code License Type  \
count           574            2
unique          574            1
top     DT.GPA.DPPG    CC BY-4.0
freq              1            2

                                           Indicator Name  \
count                                                 574
unique                                                574
top     Average grace period on new external debt comm...
freq                                                    1

                                         Short definition  \
count                                                 572
unique                                                558
top     Total external debt is debt owed to nonresiden...
freq                                                    2

                                          Long definition  \
count                                                 574
unique                                                560
top     Total external debt is debt owed to nonresiden...
freq                                                    2

                                            Source  \
count                                          574
unique                                           9
top     World Bank, International Debt Statistics.
freq                                           562

                                                    Topic  \
count                                                 574
unique                                                 21
top     Economic Policy & Debt: External debt: Debt ou...
freq                                                   77

                              Dataset Periodicity Aggregation method  \
count                             573         574                574
unique                              1           1                  3
top     International Debt Statistics      Annual                Sum
freq                              573         574                538

                               Limitations and exceptions  \
count                                                   1
unique                                                  1
top     Current population estimates for developing co...
freq                                                    1

                                         General comments
count                                                   8
unique                                                  4
top     The denominator for this indicator in previous...
freq                                                    3
Index(['Code', 'License Type', 'Indicator Name', 'Short definition',
       'Long definition', 'Source', 'Topic', 'Dataset', 'Periodicity',
       'Aggregation method', 'Limitations and exceptions', 'General comments'],
      dtype='str')

In [29]:
series_meta.columns = series_meta.columns.str.strip()

In [30]:
series_meta = series_meta.drop_duplicates()

In [31]:
series_meta_filtered = series_meta[['Code','Indicator Name','Topic']]

In [32]:
series_meta_filtered.isnull().sum()

Code              0
Indicator Name    0
Topic             0
dtype: int64

In [33]:
series_meta_filtered.rename(columns={'Series Code':'series code'},inplace=True)

In [34]:
series_meta_filtered.columns = (series_meta_filtered.columns.str.strip().str.lower().str.replace(" ", "_"))

In [35]:
pd.DataFrame(series_meta_filtered)

,code,indicator_name,topic
0,DT.GPA.DPPG,Average grace period on new external debt comm...,Economic Policy & Debt: External debt: Terms
1,DT.GPA.OFFT,Average grace period on new external debt comm...,Economic Policy & Debt: External debt: Terms
2,DT.GPA.PRVT,Average grace period on new external debt comm...,Economic Policy & Debt: External debt: Terms
3,DT.GRE.DPPG,Average grant element on new external debt com...,Economic Policy & Debt: External debt: Terms
4,DT.GRE.OFFT,Average grant element on new external debt com...,Economic Policy & Debt: External debt: Terms
...,...,...,...
569,FI.RES.TOTL.MO,Total reserves in months of imports,Economic Policy & Debt: Balance of payments: R...
570,DT.UND.OFFT.CD,"Undisbursed external debt, official creditors ...",Economic Policy & Debt: External debt: Undisbu...
571,DT.UND.PRVT.CD,"Undisbursed external debt, private creditors (...",Economic Policy & Debt: External debt: Undisbu...
572,DT.UND.DPPG.CD,"Undisbursed external debt, total (UND, current...",Economic Policy & Debt: External debt: Undisbu...
573,DT.DOD.DIMF.CD,"Use of IMF credit (DOD, current US$)",Economic Policy & Debt: External debt: Debt ou...

-----------------------------------------------Country-Series-Data--------------------------------------------

In [36]:
#Display CountrySeries  
pd.DataFrame(country_series.head())

,Type,Country Code,Series Code,Description
0,Country-Series,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",Data on Foreign Direct Investment are based on...
1,Country-Series,Afghanistan (AFG),"Population, total (SP.POP.TOTL)",Data source: United Nations World Population P...
2,Country-Series,Afghanistan (AFG),"External debt stocks, total (DOD, current US$)...","Long-term public and publicly guaranteed, long..."
3,Country-Series,Angola (AGO),"External debt stocks, total (DOD, current US$)...",Long-term public and publicly guaranteed debt ...
4,Country-Series,Angola (AGO),"Population, total (SP.POP.TOTL)",Data source: United Nations World Population P...

In [37]:
print(country_series.info())

<class 'pandas.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          375 non-null    str
 1   Country Code  375 non-null    str
 2   Series Code   375 non-null    str
 3   Description   375 non-null    str
dtypes: str(4)
memory usage: 11.8 KB
None

In [38]:
print(country_series.describe())

                  Type Country Code  \
count              375          375
unique               1          131
top     Country-Series  India (IND)
freq               375            6

                                              Series Code  \
count                                                 375
unique                                                  7
top     Foreign direct investment, net inflows in repo...
freq                                                  127

                                              Description
count                                                 375
unique                                                130
top     Data on Foreign Direct Investment are based on...
freq                                                  127

In [39]:
print(country_series.columns)

Index(['Type', 'Country Code', 'Series Code', 'Description'], dtype='str')

In [40]:
country_series.columns = country_series.columns.str.strip()
country_series = country_series.drop_duplicates()
country_series_filtered = country_series[["Country Code", "Series Code"]]
print(country_series_filtered.isnull().sum())

Country Code    0
Series Code     0
dtype: int64

In [41]:
print(country_series_filtered.columns)
pd.DataFrame(country_series_filtered)

Index(['Country Code', 'Series Code'], dtype='str')

          Country Code                                        Series Code
0    Afghanistan (AFG)  Foreign direct investment, net inflows in repo...
1    Afghanistan (AFG)                    Population, total (SP.POP.TOTL)
2    Afghanistan (AFG)  External debt stocks, total (DOD, current US$)...
3         Angola (AGO)  External debt stocks, total (DOD, current US$)...
4         Angola (AGO)                    Population, total (SP.POP.TOTL)
..                 ...                                                ...
370       Zambia (ZMB)                    Population, total (SP.POP.TOTL)
371       Zambia (ZMB)  External debt stocks, total (DOD, current US$)...
372     Zimbabwe (ZWE)  External debt stocks, total (DOD, current US$)...
373     Zimbabwe (ZWE)                    Population, total (SP.POP.TOTL)
374     Zimbabwe (ZWE)  Foreign direct investment, net inflows in repo...

[375 rows x 2 columns]

In [42]:
country_series_filtered[['country','country_code']] = country_series_filtered['Country Code'].str.replace(")", "", regex=False).str.split("(", n=1, expand=True)
country_series_filtered=country_series_filtered[['country', 'country_code', 'Series Code']]

In [43]:
print(country_series_filtered.columns)
pd.DataFrame(country_series_filtered)

Index(['country', 'country_code', 'Series Code'], dtype='str')

,country,country_code,Series Code
0,Afghanistan,AFG,"Foreign direct investment, net inflows in repo..."
1,Afghanistan,AFG,"Population, total (SP.POP.TOTL)"
2,Afghanistan,AFG,"External debt stocks, total (DOD, current US$)..."
3,Angola,AGO,"External debt stocks, total (DOD, current US$)..."
4,Angola,AGO,"Population, total (SP.POP.TOTL)"
...,...,...,...
370,Zambia,ZMB,"Population, total (SP.POP.TOTL)"
371,Zambia,ZMB,"External debt stocks, total (DOD, current US$)..."
372,Zimbabwe,ZWE,"External debt stocks, total (DOD, current US$)..."
373,Zimbabwe,ZWE,"Population, total (SP.POP.TOTL)"
374,Zimbabwe,ZWE,"Foreign direct investment, net inflows in repo..."

--------------------------------------------------Foot-Note-Meta-Data-------------------------------------

In [44]:
#Display CountrySeries  
pd.DataFrame(foot_notes.head())

,Type,Country Code,Series Code,Time Code,Description
0,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2024 (YR2024),Data on Personal Transfers and Compensation of...
1,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2023 (YR2023),Source: United Nations Conference on Trade and...
2,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2021 (YR2021),Source: United Nations Conference on Trade and...
3,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2022 (YR2022),Source: United Nations Conference on Trade and...
4,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",2021 (YR2021),Source: United Nations Conference on Trade and...

In [45]:
print(foot_notes.info())

<class 'pandas.DataFrame'>
RangeIndex: 2673 entries, 0 to 2672
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          2673 non-null   str
 1   Country Code  2673 non-null   str
 2   Series Code   2673 non-null   str
 3   Time Code     2673 non-null   str
 4   Description   2673 non-null   str
dtypes: str(5)
memory usage: 104.5 KB
None

In [46]:
print(foot_notes.describe())
print(foot_notes.columns)

            Type              Country Code  \
count       2673                      2673
unique         1                       106
top     FootNote  Iran, Islamic Rep. (IRN)
freq        2673                       143

                                              Series Code      Time Code  \
count                                                2673           2673
unique                                                 26             55
top     Foreign direct investment, net inflows in repo...  2024 (YR2024)
freq                                                 1206            208

                                              Description
count                                                2673
unique                                                 64
top     Source: United Nations Conference on Trade and...
freq                                                 1166
Index(['Type', 'Country Code', 'Series Code', 'Time Code', 'Description'], dtype='str')

In [47]:
foot_notes.columns = foot_notes.columns.str.strip()

In [48]:
foot_notes = foot_notes.drop_duplicates()

In [49]:
pd.DataFrame(foot_notes)

,Type,Country Code,Series Code,Time Code,Description
0,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2024 (YR2024),Data on Personal Transfers and Compensation of...
1,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2023 (YR2023),Source: United Nations Conference on Trade and...
2,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2021 (YR2021),Source: United Nations Conference on Trade and...
3,FootNote,Afghanistan (AFG),Personal transfers and compensation of employe...,2022 (YR2022),Source: United Nations Conference on Trade and...
4,FootNote,Afghanistan (AFG),"Foreign direct investment, net inflows in repo...",2021 (YR2021),Source: United Nations Conference on Trade and...
...,...,...,...,...,...
2668,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1974 (YR1974),Source: United Nations Conference on Trade and...
2669,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1970 (YR1970),Source: United Nations Conference on Trade and...
2670,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1973 (YR1973),Source: United Nations Conference on Trade and...
2671,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1971 (YR1971),Source: United Nations Conference on Trade and...
2672,FootNote,Zimbabwe (ZWE),"Foreign direct investment, net inflows in repo...",1976 (YR1976),Source: United Nations Conference on Trade and...

In [50]:
foot_notes[['country','country_code']] = foot_notes['Country Code'].str.replace(")","",regex=False).str.split("(",expand=True)

In [51]:
foot_notes[['year', 'Time_Code']] = foot_notes['Time Code'].str.extract(r'(\d{4})\s*\((YR\d+)\)')

In [52]:
print(foot_notes.columns)

Index(['Type', 'Country Code', 'Series Code', 'Time Code', 'Description',
       'country', 'country_code', 'year', 'Time_Code'],
      dtype='str')

In [53]:
foot_notes = foot_notes[['Type','country', 'country_code', 'Series Code','year', 'Time_Code', 'Description']]

In [54]:
foot_notes.columns = (
    foot_notes.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_"))

pd.DataFrame(foot_notes)

,type,country,country_code,series_code,year,time_code,description
0,FootNote,Afghanistan,AFG,Personal transfers and compensation of employe...,2024,YR2024,Data on Personal Transfers and Compensation of...
1,FootNote,Afghanistan,AFG,Personal transfers and compensation of employe...,2023,YR2023,Source: United Nations Conference on Trade and...
2,FootNote,Afghanistan,AFG,Personal transfers and compensation of employe...,2021,YR2021,Source: United Nations Conference on Trade and...
3,FootNote,Afghanistan,AFG,Personal transfers and compensation of employe...,2022,YR2022,Source: United Nations Conference on Trade and...
4,FootNote,Afghanistan,AFG,"Foreign direct investment, net inflows in repo...",2021,YR2021,Source: United Nations Conference on Trade and...
...,...,...,...,...,...,...,...
2668,FootNote,Zimbabwe,ZWE,"Foreign direct investment, net inflows in repo...",1974,YR1974,Source: United Nations Conference on Trade and...
2669,FootNote,Zimbabwe,ZWE,"Foreign direct investment, net inflows in repo...",1970,YR1970,Source: United Nations Conference on Trade and...
2670,FootNote,Zimbabwe,ZWE,"Foreign direct investment, net inflows in repo...",1973,YR1973,Source: United Nations Conference on Trade and...
2671,FootNote,Zimbabwe,ZWE,"Foreign direct investment, net inflows in repo...",1971,YR1971,Source: United Nations Conference on Trade and...
2672,FootNote,Zimbabwe,ZWE,"Foreign direct investment, net inflows in repo...",1976,YR1976,Source: United Nations Conference on Trade and...